package com.example.a30days.model

import com.example.a30days.R

object ExerciseDatasource {
    val dailyExercises = listOf<DailyExercise>(
        DailyExercise(
            R.string.day_one,
            R.string.day_one_exercise,
            R.drawable.day_one,
            R.string.day_one_exercise_description
        ),
        DailyExercise(
            R.string.day_two,
            R.string.day_two_exercise,
            R.drawable.day_two,
            R.string.day_two_exercise_description
        ),
        DailyExercise(
            R.string.day_three,
            R.string.day_three_exercise,
            R.drawable.day_three,
            R.string.day_three_exercise_description
        ),
        DailyExercise(
            R.string.day_four,
            R.string.day_four_exercise,
            R.drawable.day_four,
            R.string.day_four_exercise_description
        ),
        DailyExercise(
            R.string.day_five,
            R.string.day_five_exercise,
            R.drawable.day_five,
            R.string.day_five_exercise_description
        ),
        DailyExercise(
            R.string.day_six,
            R.string.day_six_exercise,
            R.drawable.day_six,
            R.string.day_six_exercise_description
        ),
        DailyExercise(
            R.string.day_seven,
            R.string.day_seven_exercise,
            R.drawable.day_seven,
            R.string.day_seven_exercise_description
        ),
        DailyExercise(
            R.string.day_eight,
            R.string.day_eight_exercise,
            R.drawable.day_eight,
            R.string.day_eight_exercise_description
        ),
        DailyExercise(
            R.string.day_nine,
            R.string.day_nine_exercise,
            R.drawable.day_nine,
            R.string.day_nine_exercise_description
        ),
        DailyExercise(
            R.string.day_ten,
            R.string.day_ten_exercise,
            R.drawable.day_ten,
            R.string.day_ten_exercise_description
        ),
        DailyExercise(
            R.string.day_eleven,
            R.string.day_eleven_exercise,
            R.drawable.day_eleven,
            R.string.day_eleven_exercise_description
        ),
        DailyExercise(
            R.string.day_twelve,
            R.string.day_twelve_exercise,
            R.drawable.day_twelve,
            R.string.day_twelve_exercise_description
        ),
        DailyExercise(
            R.string.day_thirteen,
            R.string.day_thirteen_exercise,
            R.drawable.day_thirteen,
            R.string.day_thirteen_exercise_description
        ),
        DailyExercise(
            R.string.day_fourteen,
            R.string.day_fourteen_exercise,
            R.drawable.day_fourteen,
            R.string.day_fourteen_exercise_description
        ),
        DailyExercise(
            R.string.day_fifteen,
            R.string.day_fifteen_exercise,
            R.drawable.day_fifteen,
            R.string.day_fifteen_exercise_description
        ),
        DailyExercise(
            R.string.day_sixteen,
            R.string.day_sixteen_exercise,
            R.drawable.day_sixteen,
            R.string.day_sixteen_exercise_description
        ),
        DailyExercise(
            R.string.day_seventeen,
            R.string.day_seventeen_exercise,
            R.drawable.day_seventeen,
            R.string.day_seventeen_exercise_description
        ),
        DailyExercise(
            R.string.day_eighteen,
            R.string.day_eighteen_exercise,
            R.drawable.day_eighteen,
            R.string.day_eighteen_exercise_description
        ),
        DailyExercise(
            R.string.day_nineteen,
            R.string.day_nineteen_exercise,
            R.drawable.day_nineteen,
            R.string.day_nineteen_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty,
            R.string.day_twenty_exercise,
            R.drawable.day_twenty,
            R.string.day_twenty_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_one,
            R.string.day_twenty_one_exercise,
            R.drawable.day_twenty_one,
            R.string.day_twenty_one_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_two,
            R.string.day_twenty_two_exercise,
            R.drawable.day_twenty_two,
            R.string.day_twenty_two_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_three,
            R.string.day_twenty_three_exercise,
            R.drawable.day_twenty_three,
            R.string.day_twenty_three_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_four,
            R.string.day_twenty_four_exercise,
            R.drawable.day_twenty_four,
            R.string.day_twenty_four_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_five,
            R.string.day_twenty_five_exercise,
            R.drawable.day_twenty_five,
            R.string.day_twenty_five_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_six,
            R.string.day_twenty_six_exercise,
            R.drawable.day_twenty_six,
            R.string.day_twenty_six_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_seven,
            R.string.day_twenty_seven_exercise,
            R.drawable.day_twenty_seven,
            R.string.day_twenty_seven_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_eight,
            R.string.day_twenty_eight_exercise,
            R.drawable.day_twenty_eight,
            R.string.day_twenty_eight_exercise_description
        ),
        DailyExercise(
            R.string.day_twenty_nine,
            R.string.day_twenty_nine_exercise,
            R.drawable.day_twenty_nine,
            R.string.day_twenty_nine_exercise_description
        ),
        DailyExercise(
            R.string.day_thirty,
            R.string.day_thirty_exercise,
            R.drawable.day_thirty,
            R.string.day_thirty_exercise_description
        )
    )
}